name: my_first_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  footer: ^0.0.4 
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  webview_flutter: ^4.10.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  #   - assets/avatar_3.png
  #   - assets/avatar_4.png
  #   - assets/avatar_5.png
  #   - assets/avatar_6.png
  #   - assets/avatar_7.png
  #   - assets/thumbnail_1.png